name:                master-minds
version:             0.1.0.0
github:              "githubuser/master-minds"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/master-minds#readme>

dependencies:
- base >= 4.7 && < 5
- monad-par >= 0.3.5
- parallel >= 3.2.2.0


library:
  source-dirs: src

executables:
  master-minds-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N8
    - -eventlog
    dependencies:
    - master-minds
    - monad-par >= 0.3.5
    - parallel >= 3.2.2.0

tests:
  master-minds-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -eventlog
    dependencies:
    - master-minds
